-- Dữ liệu đầy đủ cho 6 làng khảo sát (Cự Đà, Ước Lễ, Hạ Thái, Làng Cựu,
-- Làng Chuông, Phú Vinh). Thay thế toàn bộ luồng import Excel cho bảng này —
-- không cần file .xlsx để có đủ hồ sơ làng.
-- Idempotent: UPSERT theo id cố định; slug NOT NULL/UNIQUE bật sau khi mọi
-- dòng đã có giá trị slug hợp lệ (an toàn để chạy lại nhiều lần).

INSERT INTO "villages" ("id", "name", "aliases", "admin_location", "google_maps_link", "founded_period", "brand_identity", "name_meaning", "main_occupations", "natural_features", "site_selection_history", "morphology_description", "created_at", "updated_at", "slug")
VALUES
  ('00000000-0000-0000-0000-000000000001', 'Làng Ước Lễ', ARRAY['làng Chảy']::text[], 'xã Dân Hòa, Hà Nội (trước là xã Tân Ước, huyện Thanh Oai, Hà Nội)', NULL, 'TK 16', 'Làng giò chả', 'Ước, Lễ là chữ dùng xuất phát từ lời của Khổng Tử (Bác học dĩ văn, ước chi dĩ lễ), ý nói muốn học rộng thì phải dựa vào văn (tức văn hoá); học đã rộng rồi thì phải chế định (Ước) bằng Lễ, ấy là điều cần thiết của người học rộng. Lấy Ước Lễ đặt tên làng thể hiện quan niệm trong cuộc sống phải luôn luôn giữ lễ.', ARRAY['Làm giò chả', 'làm nông']::text[], 'Làng có hệ thống cây xanh mặt nước bao quanh, không có các hộ chăn nuôi quy mô lớn cũng như hộ sản xuất quy mô lớn ảnh hưởng đến ô nhiễm môi trường', 'ngày xưa, ông Lữ Gia đánh trận thua, chạy về tới cây đa trước cổng làng đầu đã bị chém gần lìa, gặp một bà cụ người làng, hỏi: Người bị chém đứt đầu có sống được không? Bà cụ nói: Sống thế nào được. Ông bèn dứt đầu ra khỏi cổ rồi ngã xuống ngựa. Dân tôn ông làm Thành hoàng, thờ cúng ở đình cho đến nay.', 'Cấu trúc mạng lưới giao thông làng Ước Lễ là cấu trúc hình xương cá, đặc trưng cấu trúc làng truyền thống vùng đồng bằng Bắc Bộ. Đường làng chính đóng vai trò là trục xương sống kết nối tất cả các không gian trong làng; các công trình công cộng truyền thống nằm tại các vị trí quan trọng về mặt hình thái hình học trên đường làng chính.', '2026-09-21T02:53:32.052Z', '2026-09-21T07:18:35.222Z', 'lang-uoc-le'),
  ('01000000-0000-0000-0000-000000000001', 'Làng Cự Đà', ARRAY['làng Ngô Khê']::text[], 'xã Bình Minh, Hà Nội (trước là xã Cự Khê, huyện Thanh Oai, Hà Nội)', NULL, 'TK1', NULL, 'tên Ngô Khê: Ngô là vùng đất mà họ NGô sinh sống, Khê theo tiếng Hán là Khe lạch. Có học giả lại cho rằng Ngô trong Ngô Khê là để chỉ cây duối, cây vông, nhũng loại cây mọc rất nhiều trong làng. 
TK17 đổi tên làng Cự Đà, tên gọi làng cũ của họ Trịnh ở THanh Hóa', ARRAY['nghề làm miến', 'nghề làm tương']::text[], 'Làng chạy dài ven sông Nhuệ', 'Nằm ở vị trí thuận lợi cho giao thông đường thủy, phát triển hoạt động giao lưu buôn bán với kinh thành và các vùng khác. Cự Đà cách con đường Thiên lý Tây đạo chạy từ vùng núi phía Tây qua huyện Chương Đức về vùng đồng bằng 5km (theo sách "Lư sử điển yếu điều lệ" (1974))', 'Cấu trúc của ngôi làng theo hình lược, bám ven sông Nhuệ. Từ đường làng lớn tỏa ra hàng chục con ngõ đâm ngang, hẹp, lát gạch đỏ. Cổng ngõ nào cũng chạy ra đến bờ sông với những thềm gạch vươn tận mép ước. Quy hoạch tự nhiên của làng đúng theo mô hình “nhất cận thị, nhì cận giang” điển hình cho làng Việt cổ vừa nông nghiệp, vừa thương mại.', '2026-09-21T02:53:49.354Z', '2026-09-21T07:49:36.546Z', 'cu-da'),
  ('fdd98e46-3b65-490d-aadc-dbb90eab321d', 'Làng Hạ Thái', ARRAY['Cự Tràng (tên cũ)', 'Đông Thái (tên cũ)']::text[], 'Xã Hồng Vân, Hà Nội', NULL, 'Khoảng thế kỷ XVII (nghề sơn) / Thế kỷ XVIII (làng)', 'Làng nghề sơn mài truyền thống Hạ Thái - Điểm du lịch làng nghề.', '"Hạ Thái" có nghĩa là "vùng đất thấp, bình yên và thái bình".', ARRAY['Nghề sơn mài truyền thống (từ sơn son thiếp vàng sang sơn mài mỹ nghệ', 'sản xuất tranh và đồ gia dụng xuất khẩu).']::text[], 'Địa hình bằng phẳng, nằm trong vùng khí hậu nhiệt đới gió mùa, có sông Tô Lịch chảy qua.', 'Nằm ở vùng đồng bằng bồi tụ, ven sông Tô Lịch, thuận lợi giao thông đường thủy và gần các trục giao thông quan trọng (QL1A, đường sắt Bắc Nam, đường cao tốc Pháp Vân - Cầu Giẽ).', 'Cấu trúc "Xương cá hội tụ". Các trục ngõ nhánh đổ về trục đường chính hướng ra đình làng và khu không gian sản xuất chung ven trục lộ lớn.', '2026-09-21T02:54:19.878Z', '2026-09-21T07:18:32.033Z', 'ha-thai'),
  ('c33319de-4845-41bf-94c1-3fa501e5e867', 'Làng Cựu', ARRAY[]::text[], 'Xã Chuyên Mỹ, TP. Hà Nội (trước xã Vân Từ, huyện Phú Xuyên, TP. Hà Nội)', NULL, 'khoảng thế kỷ XIII', 'Làng nghề may Comple - Veston, Làng biệt thự Pháp cổ', 'Tên gọi Làng Cựu mang ý nghĩa gốc là "Kẻ Cựu", dùng để chỉ vùng đất cổ kính, lâu đời.', ARRAY['Trước đây', 'người dân trong làng chủ yếu làm nông và làm may Comple - Veston. Những năm gần đây', 'người dân làm nhiều các nghề khác nhau: nông nghiệp', 'may mặc', 'dày da', 'buôn bán....']::text[], 'Địa hình đồng chiêm trũng: Xưa kia, làng tọa lạc trên một vùng đồng chiêm trũng thuộc phía Tây Nam huyện Phú Xuyên, mỗi năm chỉ cấy được một vụ lúa. Địa hình này khiến khu vực phía Nam của đường làng chính trước đây thường xuyên bị ngập nước vào mùa nước lên. Phải đến những năm 1960, nhờ sự biến đổi của chế độ thủy văn, làng mới không còn bị ngập nữa. Làng được bao bọc xung quanh bởi hệ thống đồng ruộng rộng lớn. Cảnh quan cánh đồng lúa xanh mướt hay vàng ươm vào mùa gặt không chỉ tạo nên khung cảnh yên bình tiêu biểu của làng quê mà còn là nguồn cung cấp thực phẩm chính cho người dân.', 'Làng được xây dựng trên một gò đất cao của vùng đồng chiêm trũng, mỗi năm làng chỉ cấy được một vụ lúa. Làng cũng được tiếp cận với 1 nhánh của sông Nhuệ (vị trí ao làng gần Đình hiện nay).', NULL, '2026-09-21T02:54:19.976Z', '2026-09-21T07:18:33.530Z', 'lang-cuu'),
  ('09ee09b0-41f2-429c-a515-0cd2592edc44', 'Làng Chuông', ARRAY['Trang Thì Trung (hoặc trang Thời Trung): Đây là tên gọi ban đầu của làng từ thế kỷ thứ 8']::text[], 'Xã Thanh Oai, TP. Hà Nội (trước xã Phương Trung, huyện Thanh Oai, Hà Nội)', NULL, 'thế kỷ thứ 8 (cụ thể là vào năm 791 - năm Tân Mùi)', 'Làng Nón', 'Từ "Chuông" không chỉ đơn thuần là tên làng mà còn mang ý nghĩa ngợi ca nghề truyền thống nơi đây. "Chuông" mang ý nghĩa chỉ chiếc nón đẹp, được làm công phu và tỉ mỉ như việc đúc chuông. Lời ca ngợi này được đúc kết qua câu đối cổ truyền lại: "Ngọn lá xuân phong khuôn khéo lựa / Sợi vàng tạo hóa nắn nên Chuông"', ARRAY['Việc làm nón được thực hiện 100% bằng tay', 'đòi hỏi sự khéo léo qua nhiều công đoạn phức tạp từ phơi', 'vò', 'hơ diêm sinh', 'là phẳng lá cho đến lợp nón và thắt nón. Nón Chuông luôn nổi bật nhờ kết cấu chèn một lớp mo nang ở giữa hai lớp lá giúp nón cực kỳ bền chắc']::text[], 'Làng là nằm ven đê sông Đáy. Trước đây, làng sở hữu một hệ sinh thái tự nhiên phong phú với nhiều diện tích mặt nước, cây xanh và đa dạng các loài động vật. Làng có một hệ thống mặt nước tự nhiên rộng lớn bao gồm các ao hồ, kênh rạch và đặc biệt là rất nhiều chiếc giếng làng lớn với đường kính từ 15-18m. Hiện nay, do tốc độ xây dựng, lấn chiếm đất đai và mật độ dân cư gia tăng quá nhanh, hệ sinh thái cảnh quan tự nhiên của làng đã bị biến đổi và suy giảm nghiêm trọng về cả số lượng lẫn chất lượng.', 'Ngôi làng này đã tồn tại từ thời kỳ nước ta thuộc ách đô hộ của nhà Đường (năm 603-906). Tương truyền, làng từng có vai trò chiến lược quan trọng khi được danh tướng Phùng Hưng chọn làm nơi đóng đồn binh, cho binh lính nghỉ ngơi và luyện quân . Dọc theo dòng sông Đáy, từ bàn đạp là làng Chuông, nghĩa quân đã tiến qua Thạch Bích, Triều Khúc để đánh thẳng vào thành Tống Bình, lật đổ ách thống trị của nhà Đường và giành quyền tự chủ cho đất nước vào thế kỷ thứ VII', NULL, '2026-09-21T02:54:20.078Z', '2026-09-21T07:18:32.871Z', 'lang-chuong'),
  ('8216fe86-f66d-4b19-904b-cbdee0bf1eba', 'Làng Phú Vinh', ARRAY['Phú Hoa Trang (Trời phú cho dân có bàn tay lụa)']::text[], 'Xã Phú Nghĩa, TP Hà Nội (trước là xã Phú Nghĩa, huyện Chương Mỹ, thành phố Hà Nội)', 'https://www.google.com/maps/d/u/0/edit?mid=1xHfNYeAgUeXDI4Sof9d3GT669B_PDXY&usp=sharing', 'Từ năm 1700 (đầu TK 17)', 'Làng nghề mây tre đan truyền thống đã tồn tại và phát triển hơn 400 năm', 'Tên gọi ban đầu là làng Phú Hoa Trang (Trời phú cho dân có bàn tay lụa), vì người dân nơi đây có bàn tay khéo léo, điệu nghệ, giỏi đan lát mây tre.
Phú Vinh (Lời chúc cát lành, biểu trưng cho sự giàu đẹp và vinh hiển)', ARRAY['Làng Phú Vinh được biết đến là nguồn cội của rất nhiều thế hệ nghệ nhân tài hoa từng làm ra nhiều sản phẩm mây tre đan độc đáo. Những người nghệ nhân có những kỹ năng', 'kỹ thuật đường đan tỉ mỉ', 'cầu kì', 'sản phẩm họ làm thường có hoa văn đan tết tinh xảo', 'độc đáo', 'mà người ta chỉ tìm thấy ở làng nghề Phú Vinh. Theo lịch sử hàng trăm năm của làng nghề', 'mây tre đan Phú Vinh luôn được nhiều người biết đến bởi giá trị truyền thống', 'cũng như tính nghệ thuật đỉnh cao qua sản phẩm của các nghệ nhân làng nghề.']::text[], 'Làng Phú Vinh có bị trí thuận lợi đi qua một số tuyến quốc lộ và tỉnh lộ quan trọng thuận lợi cho việc tiếp cận của các đoàn khách du lịch. Về đặc điểm tự nhiên thì làng Phú Vinh nằm ở ven đê sông Đáy nên vốn có một hệ sinh thái trù phú và quỹ đất nông nghiệp và những cảnh quan nông nghiệp đặc trưng của làng ngoại thành Hà Nội. Đây cũng là một ưu điểm bổ trợ cho việc quy hoạch và phát triển các sản phẩm du lịch đến làng nghề. Ngày nay, tốc độ, mật độ xây dựng và cư trú của người dân gia tăng nhanh chóng và vì vậy lấn chiếm diện tích lớn của hệ sinh thái cảnh quan tự nhiên', NULL, 'làng có hình dáng của một chiếc lá, được tạo hình rõ nét bởi một bên là sông Hồng và một bên đê bao quanh khép kín. Với trục chính chạy xuyên suốt từ đầu đến cuối làng, các ngõ song song tạo thành gân lá.', '2026-09-21T02:54:20.179Z', '2026-09-21T07:18:34.352Z', 'phu-vinh')
ON CONFLICT (id) DO UPDATE SET
  "name" = EXCLUDED."name",
  "aliases" = EXCLUDED."aliases",
  "admin_location" = EXCLUDED."admin_location",
  "google_maps_link" = EXCLUDED."google_maps_link",
  "founded_period" = EXCLUDED."founded_period",
  "brand_identity" = EXCLUDED."brand_identity",
  "name_meaning" = EXCLUDED."name_meaning",
  "main_occupations" = EXCLUDED."main_occupations",
  "natural_features" = EXCLUDED."natural_features",
  "site_selection_history" = EXCLUDED."site_selection_history",
  "morphology_description" = EXCLUDED."morphology_description",
  "created_at" = EXCLUDED."created_at",
  "updated_at" = EXCLUDED."updated_at",
  "slug" = EXCLUDED."slug";

ALTER TABLE villages ALTER COLUMN slug SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_villages_slug') THEN
    ALTER TABLE villages ADD CONSTRAINT uq_villages_slug UNIQUE (slug);
  END IF;
END $$;
