-- 16 câu chuyện lịch sử/sự kiện/phong tục/truyền thuyết.
-- Idempotent: UPSERT theo id cố định.

INSERT INTO "history_stories" ("id", "village_id", "site_id", "type", "title", "body_text", "media_ids", "created_at", "updated_at")
VALUES
  ('41000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', NULL, 'lich_su', 'Lịch sử làng', 'Ước Lễ nổi tiếng với nghề làm giò chả. Nghề làm giò chả ở làng Ước Lễ có cách đây gần 500 năm. Theo truyền miệng, thời nhà Mạc (1527 - 1592) có một cung tần trong triều đình vốn là người làng Ước Lễ về xây cổng làng và dạy cho dân làng nghề giò chả. Từ đó cha truyền con nối, nghề giò chả trở thành nghề truyền thống của làng Ước Lễ.', NULL, '2026-09-21T02:54:19.176Z', '2026-09-21T07:18:35.222Z'),
  ('41000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', NULL, 'su_kien', 'Sự kiện lịch sử đã diễn ra', 'Theo thông tin lịch sử, cổng làng Ước Lễ được xây dựng vào năm 1851 (đời vua Tự Đức). Làng Ước Lễ là một trong số ít làng xây dựng được quỹ cứu trợ người dân trong những lúc gặp khó khăn: loạn lạc, mất mùa,...  có những lúc quỹ cứu trợ này lên tới 2000 đồng Đông Dương. Theo luật lệ thời đó, các làng xây dựng được quỹ cứu trợ 1000 đồng Đông Dương đã được vua ban thưởng, nên làng Ước Lễ đã được vua ngự ban cho biển “Mỹ tục khả phong” (Phong tục hay nên theo). Đến thời chống Pháp, lầu trên của cổng đã bị bắn phá đổ cùng với biển trên. Người dân làng đã cúng tiến và xây dựng lại tầng trên cùng với làm lại biển chữ từ khoảng năm 2000.', NULL, '2026-09-21T02:54:19.176Z', '2026-09-21T07:18:35.222Z'),
  ('41000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000001', NULL, 'phong_tuc', 'Phong tục', 'ở Ước Lễ còn có một phong tục vô cùng độc đáo, đó là tục ăn “Tết bù” vào ngày rằm tháng Giêng. Phong tục này xuất phát từ việc dân làng thường bận làm giò chả phục vụ nhu cầu ăn Tết của người dân khắp nơi nên không thể chuẩn bị Tết chu đáo. Vì thế, rằm tháng Giêng mới là dịp các gia đình ở Ước Lễ quây quần ăn “Tết bù”.', NULL, '2026-09-21T02:54:19.176Z', '2026-09-21T07:18:35.222Z'),
  ('41000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000001', NULL, 'truyen_thuyet', 'Truyền thuyết', 'ngày xưa, ông Lữ Gia đánh trận thua, chạy về tới cây đa trước cổng làng đầu đã bị chém gần lìa, gặp một bà cụ người làng, hỏi: Người bị chém đứt đầu có sống được không? Bà cụ nói: Sống thế nào được. Ông bèn dứt đầu ra khỏi cổ rồi ngã xuống ngựa. Dân tôn ông làm Thành hoàng, thờ cúng ở đình cho đến nay.
Truyền thuyết kể rằng, mảnh đất giữa làng xưa kia là nền của kho dự trữ thóc gạo do làng tự lập, gọi là quỹ “Nghĩa thương”. Làng cử người coi sóc, nhằm giúp đỡ dân nghèo trong làng và người cơ nhỡ. Vua Tự Đức kinh lý qua thấy phong tục đẹp, phong cho bốn chữ “Mỹ tục khả phong”. Bản hương ước lập năm 1928 có 106 điều, trong đó có một điều rất hay, tôi cho rằng ít có làng quê xứ Bắc xưa nào đề cập đến: “Đi ăn cỗ cấm lấy phần”.', NULL, '2026-09-21T02:54:19.176Z', '2026-09-21T07:18:35.222Z'),
  ('20d0d147-a7ca-4da1-9b89-ec9a05b9f9d0', '01000000-0000-0000-0000-000000000001', NULL, 'phong_tuc', 'Phong tục', 'Hàng năm lễ hội làng ngày 14 tháng giêng phải khấn cụ Hoằng Thông trước, cụ Vũ Lôi Hùng Uy sau. Nhưng ngày 12 tháng 5 làng cùng nhiều làng khác thì dọc sông Nhuệ làm lễ tế cụ Vũ Lôi Hùng Uy. Đây là ngày đầu mùa mưa lụt cũng là lễ Tịch Điền', NULL, '2026-09-21T07:18:17.766Z', '2026-09-21T07:18:17.766Z'),
  ('41ddc363-b834-43b0-88d0-ef5c586f1a58', '01000000-0000-0000-0000-000000000001', NULL, 'truyen_thuyet', 'Truyền thuyết', 'Khi dân đến ở, chưa được triều đình phong Thành hoàng, chưa có người bảo vệ, dọc 2 bên sông thờ 1 vị thần tưởng tượng ở trên trời Vũ Lôi Hùng Uy, để cầu mưa thuận gió hòa và bảo vệ dân làng. Sau này cần có nhân thần chính thức làm thần hoàng làng . Ngày 14 tháng giêng cuối nhà Lê, phong cụ Hoàng Thông là Thành hoàng làng. Cụ là mưu sĩ của cụ Trần Vĩ - bố nuôi của Đinh Bộ Lĩnh, hoạch định cho cụ Trần Vĩ và vua Đinh Bộ Lĩnh sách lược quản lý đất nước và phát triển kinh tế. Khi Đinh Bộ Lĩnh chưa đánh xong 12 sứ quân thì cụ đã mất, để ghi nhớ công lao của cụ nên cụ được phong làm thành hoàng làng Cự Đà, nhưng gọi tránh chữ Hoàng nên gọi là Phả độ Hoằng Thông, được phong là Quang Ý Đại Vương (sáng cả vùng rộng). Sau này khi làm hồ sơ làng thì nhân thần tưởng tượng không được công nhận nên đã đưa ông Vũ Lôi Hùng Uy là 1 vị tướng thời Hùng Vương đánh giặc Ân, được phong Linh Thúy Đại Vương.', NULL, '2026-09-21T07:18:17.766Z', '2026-09-21T07:18:17.766Z'),
  ('4d609f72-f94d-4fba-8d21-8e15ad1e4977', '01000000-0000-0000-0000-000000000001', NULL, 'lich_su', 'Lịch sử làng', 'Từ thế kỷ 16 đến đầu thế kỷ 17, làng phát triển cực thịnh về mọi mặt kinh tế, văn hóa,…, việc kinh doanh buôn bán của dân làng Cự đà, nhất là dòng họ Trịnh, phát triển rất mạnh vượt ra khỏi phạm vi của làng để vươn tới các thành phố lớn. Tại các thành phố, thị xã lớn như Hà nội, Hải Phòng, Hà Đông, Sơn Tây, Sài gòn,… đã thất xuất hiện nhiều cửa hiệu buôn lớn của người Cự đà. Nghề làm tương và nghề buôn bán là hai ngành kinh tế xương sống của làng. Bên cạnh đó, nông nghiệp phát triển cũng mạnh mẽ. 
Những năm 1920-1940 của thế kỷ trước, người làng đua nhau ra Hà nội lập xưởng, làm chủ nhà máy, chủ cửa hàng, tiệm buôn khá đông. Một loạt tên tuổi các nhà giàu Hà nội lấy tên hiệu bắt đầu bằng chữ Cự như Cự Doanh, Cự Chân, Cự Phát,… chính là người Cự Đà. Do đó, làng Cự đà trong những năm đầu thế kỷ 20 thực chất là làng thương mại ven đô giàu có, điều này kiến giải cho kiến trúc pha trộn nét Đông – Tây độc đáo của làng Cự đà. Theo tài liệu Cự Đà thôn địa bạ ghi vào năm Gia Long 4 (1805) tổng diện tích đất đai tại thôn Cự Đà tại thời điểm này là 183 mẫu, 5 sào, 11 thước, 4 tấc (trong đó bao gồm đất ở , ruộng công, ruộng thuê, đất đình chùa đền miếu, vườn ao). Ngoài ra còn có 7 mẫu , 4 sào thổ phụ và đất gò, đống. Tổng cộng là 190 mẫu, 9 sào, 11 thước, 4 tấc, bằng khoảng 68 ha. Về quá trình phát triển, giai đoạn đầu, người dân tới làng sinh sống chủ yếu ở giữa làng. Điều này được minh chứng qua mật độ dày đặc của các ngôi nhà có niên đại lâu đời ở giữa làng. Về sau nhiều dòng họ đến đây sinh sống, người dân đã mở rộng địa bàn sinh sống sang 2 bên. Hiện nay, người dân còn làm nhà ở ngay bờ sông, nơi trước kia chủ yếu làm bến đồ thuyền', NULL, '2026-09-21T07:18:17.766Z', '2026-09-21T07:18:17.766Z'),
  ('4bdca793-e2ea-474f-aa67-10f0ae5557ab', 'fdd98e46-3b65-490d-aadc-dbb90eab321d', NULL, 'lich_su', 'Lịch sử làng', 'Làng Hạ Thái là một làng có lịch sử lâu đời ở đồng bằng Bắc Bộ, thuộc xã Duyên Thái, huyện Thường Tín, Hà Nội. Nghề sơn ở đây được cho là đã hình thành trên 200 năm, có từ trước khi xây dựng đình làng (1780). Trước đây, làng có tên là Cự Tràng (gồm làng Duyên Trường và Hạ Thái), sau đổi thành Đông Thái, và nay là Hạ Thái. Xuất phát điểm là một làng nông nghiệp, Hạ Thái đã tận dụng lợi thế gần sông Tô Lịch và các trục giao thông thủy, bộ để phát triển đa dạng ngành nghề, trong đó nghề sơn nổi bật và trở thành thương hiệu riêng.
 
 Nghề sơn mài Hạ Thái gắn liền với tên tuổi của cụ Đinh Văn Thành, một giảng viên người làng tại trường Mỹ thuật Đông Dương. Vào những năm 1930, cụ đã đưa kỹ thuật sơn mài từ trường về truyền dạy cho người dân trong làng, mở ra một giai đoạn phát triển mới cho nghề, từ sơn son thiếp vàng thuần túy (phục vụ vua chúa) sang sơn mài mỹ nghệ với các tác phẩm nghệ thuật đa dạng. Ngày 08/12/2020, Làng nghề sơn mài Hạ Thái được UBND thành phố Hà Nội công nhận là điểm du lịch. Năm 2017, Đình Hạ Thái được xếp hạng là di tích quốc gia.', NULL, '2026-09-21T07:18:32.033Z', '2026-09-21T07:18:32.033Z'),
  ('8ba64392-e29c-4942-bcf1-10dd49b2db73', 'fdd98e46-3b65-490d-aadc-dbb90eab321d', NULL, 'truyen_thuyet', 'Truyền thuyết', 'Truyền thuyết về bà Đinh Thị Trạch (bà Lạy): Theo thần phả, vùng đất làng Hạ Thái xưa kia hoang vu, có một con hổ dữ (hổ lang) thường xuyên quấy phá, bắt người và gia súc. Không thể thu phục, dân làng đành phải cống nạp cho hổ một người vào ngày 10/11 hàng năm. Một người đàn bà không chồng con là bà Lạy, thấu hiểu nỗi đau của dân làng, đã tự nguyện xin dâng mình cho hổ để chấm dứt nạn cống nạp. Từ ngày bà bị hổ bắt đi mất, dân làng không còn thấy hổ quay lại. Để tưởng nhớ công ơn, bà được tôn làm Thành hoàng và ngày 10/11 trở thành ngày lễ hội chính của làng.
 
 Truyền thuyết về ông Bùi Sĩ Lương: Ông là quan võ thời Lê (1544-1597), người thông minh, văn võ song toàn, có công lớn trong việc phò Lê diệt Mạc. Khi đến vùng đất Hạ Thái, ông nhận thấy nơi đây có thế đất đẹp (rồng chầu hổ phục), bèn chọn lập gia trang và dạy dân chúng lập nghiệp. Sau khi mất, ông cũng được dân làng tôn là Thành hoàng và thờ phụng tại Đìn', NULL, '2026-09-21T07:18:32.033Z', '2026-09-21T07:18:32.033Z'),
  ('d87f2ef2-2a17-46c5-9e51-69fa829da0c4', 'fdd98e46-3b65-490d-aadc-dbb90eab321d', NULL, 'su_kien', 'Sự kiện lịch sử đã diễn ra', 'hời gian Sự kiện Ghi chú
 Khoảng thế kỷ XVII Nghề sơn bắt đầu hình thành tại làng, chủ yếu là sơn son thiếp vàng, được gọi là làng nghề "dâng vua". 
 Khoảng năm 1780 Đình làng Hạ Thái được dựng và khánh thành (ngày rằm tháng 10 năm Canh Tý). 
 Khoảng năm 1799 Chùa Phúc Thái (chùa làng) có chuông đồng được khắc ghi niên đại
 Những năm 1930 Cụ Đinh Văn Thành (giảng viên trường Mỹ thuật Đông Dương) đưa kỹ thuật sơn mài về làng, tạo bước ngoặt cho nghề. Đánh dấu sự ra đời của tranh sơn mài hiện đại Hạ Thái.
 Trước 1980 Nghề sơn mài chịu ảnh hưởng bởi các cơ chế kinh tế khác nhau: trước 1945 sản xuất đồ thờ; 1945-1989 thời kỳ hợp tác xã bao cấp; từ 1989 đến nay tự sản tự tiêu, hình thành các doanh nghiệp tư nhân
 Khoảng năm 2006 Cụm công nghiệp làng nghề sơn mài Hạ Thái được hình thành và quy hoạch, tập trung các xưởng sản xuất[citation:8]. 
 2017 Đình Hạ Thái được Bộ Văn hóa Thể thao và Du lịch xếp hạng là di tích quốc gia (Quyết định số 824/QĐ-BVHTTDL, đợt 1/2017). 
 08/12/2020 Làng nghề sơn mài Hạ Thái được UBND thành phố Hà Nội công nhận là điểm du lịch (Quyết định số 5543/QĐ-UBND)', NULL, '2026-09-21T07:18:32.033Z', '2026-09-21T07:18:32.033Z'),
  ('2ae41fd7-5978-43a6-9c30-1e32f79693f4', '09ee09b0-41f2-429c-a515-0cd2592edc44', NULL, 'su_kien', 'Sự kiện lịch sử đã diễn ra', 'Tháng Chín năm Đinh Mùi (tháng 10 năm 1847), Nguyễn Phúc Thì lên ngôi, năm sau (1848 – Mậu Thân) đặt niên hiệu và Tự Đức thì ngôi làng kiêng tên húy của vua nên xã Thì Trung và tổng Thì Trung phải đổi tên thành Phương Trung cùng các xã trong huyện Thanh Oai. Những dòng họ lớn trong làng là Lê Văn, Phạm. Ở cổng đinh làng có khắc đôi câu đối khẳng định vị thế của làng: 
“Thì Trung được đất tốt, âm trợ dương phù, ngoài chấn vũ công, muôn thuở trường tồn”.', NULL, '2026-09-21T07:18:32.871Z', '2026-09-21T07:18:32.871Z'),
  ('684ce0eb-c72d-45a8-96fa-b56ce4414fa7', '09ee09b0-41f2-429c-a515-0cd2592edc44', NULL, 'lich_su', 'Lịch sử làng', 'Làng Chuông là một làng quê truyền thống lâu đời có từ thời xa xưa nằm giữa trung tâm tỉnh Hà Tây cũ nay là Thành Phố Hà Nội. Vào thế kỷ thứ 8 - 791 năm Tân Mùi, theo các bậc cao niên trong làng thì ban đầu làng Chuông có tên là Trang Thì Trung, về sau đông dân hơn nên được mở rộng thành làng. Đầu thời Lên Sơ, làng Chuông đã rất đông đúc. 
Làng Chuông là một làng nghề nổi tiếng cả nước với truyền thống làm nón lâu đời thông qua sản phẩm nón lá. Người dân làng Chuông sống chủ yếu bằng nghề làm nón lá và làm ruộng. Không nhiều người dân trong làng biết chiếc nón xuất hiện từ khi nào nhưng trong ca dao xưa đã có câu “Nón Chuông, khua lụa, quai thao làng Đơ”.', NULL, '2026-09-21T07:18:32.871Z', '2026-09-21T07:18:32.871Z'),
  ('8bfaebe0-a495-419c-b3d8-7f5b3124d041', 'c33319de-4845-41bf-94c1-3fa501e5e867', NULL, 'lich_su', 'Lịch sử làng', 'Làng Cựu là một làng cổ, từ đời vua Lê Thánh Tông làng thuộc phủ Thường Tín, trấn Sơn Nam. Trước cách mạng tháng Tám, làng thuộc xã Vân Hoàng, huyện Phú Xuyên.
Làng được thành lập từ lâu, người thành lập làng là Trần Ninh Thuận. Theo gia phả họ trần kể lại: Đầu thế kỉ 13, trước kia làng là khu vực vùng chiêm trũng, hoang vu chỉ có toàn cây cỏ. Cụ tổ của làng là Trần Ninh Thuận làm nghề chài lưới kiếm cá xuôi theo dòng sông Nhuệ xuống tới vùng này thấy có vài đồi gò hiện lên trên vùng đất trũng nên đã quyết định ở lại sinh sống, theo thời gian các ngư dân làm nghề chài lưới đi qua thấy vùng này có người ở nên cũng quyết đinh ở lại lập làng. Đặt tên làng là Cựu.', NULL, '2026-09-21T07:18:33.530Z', '2026-09-21T07:18:33.530Z'),
  ('a2ce6e31-9884-4b84-8115-1097b9acf415', 'c33319de-4845-41bf-94c1-3fa501e5e867', NULL, 'su_kien', 'Sự kiện lịch sử đã diễn ra', 'Biến cố hỏa hoạn năm 1921: Bước ngoặt lớn nhất của làng xảy ra vào năm 1921 khi một gia đình nấu ăn bất cẩn đã gây ra trận hỏa hoạn lớn. Do phần lớn là nhà tranh tre nứa lá, ngọn lửa đã nhanh chóng thiêu rụi 2/3 số nhà cửa trong làng. Đối diện với cảnh mất mùa, đói kém lại thêm nhà cửa hóa tro bụi, người dân khốn quẫn buộc phải khăn gói rời làng ra Hà Nội tìm đường mưu sinh. Hai người đầu tiên bước chân vào nghề may là anh em ông Phúc Mỹ, Phúc Hưng. Thấy làm ăn tốt, các ông bắt đầu về làng kéo mọi người đi làm cùng. Chẳng ai ngờ những đôi bàn tay chai sần bởi cuốc với cày lại có thể khéo léo tạo ra những bộ veston, bộ đầm đẹp đến thế. Họ may chủ yếu cho người Pháp và lớp người giàu ở Hà Nội.Từ những người nông dân cầm cuốc, người làng Cựu đã bén duyên với nghề may (bắt đầu từ hai anh em ông Phúc Mỹ, Phúc Hưng) và nhanh chóng phất lên, trở thành những "thợ may đệ nhất Hà Thành" . Họ chuyên may đo cho người Pháp và giới nhà giàu ở Hà Nội, sau đó bao thầu luôn cả nghề buôn vải, mở rộng thị trường vào tận Sài Gòn - Chợ Lớn. Kiến thiết quê hương (1920 - 1945): Thành công từ nghề may giúp người làng Cựu từ nông dân trở thành những triệu phú . Sự giàu có này được họ mang về quê hương để xây dựng hàng loạt biệt thự tráng lệ, nguy nga mang phong cách giao thoa Á - Âu (với vòm cuốn, mái chảy, gỗ lim, ngói mũi...) trong suốt giai đoạn từ năm 1920 đến 1945', NULL, '2026-09-21T07:18:33.530Z', '2026-09-21T07:18:33.530Z'),
  ('def65a87-2115-409a-a7d6-93bb6e4cb852', 'c33319de-4845-41bf-94c1-3fa501e5e867', NULL, 'truyen_thuyet', 'Truyền thuyết', 'Theo truyền thuyết đó là sự tích về cụ Thế tổ thứ 2 Trần miêu thuật nuôi hổ để trông coi gia sản. Cụ mặc thường phục giả danh để thử hổ xem việc trông coi có chăm chỉ không. Sự việc đã gây nên tai họa, hổ tát nhầm vào cụ, cụ đã tử vong. Di hài của thế tổ được mang đi chôn tại Hạ Thái, Thường Tín và ở thôn Cự, xã Vân Từ, Phú Xuyên nơi có hai nấm mồ máu do Hổ vun lại cùng gọi là Cổ Bồng.', NULL, '2026-09-21T07:18:33.530Z', '2026-09-21T07:18:33.530Z'),
  ('1cd17162-17ac-4875-8b8d-f55f8da005ef', '8216fe86-f66d-4b19-904b-cbdee0bf1eba', NULL, 'lich_su', 'Lịch sử làng', 'Nghề mây tre đan truyền thống đã tồn tại và phát triển hơn 400 năm. Làng Phú Vinh được hình thành từ năm 1700, với tên gọi ban đầu là làng Phú Hoa Trang (Trời phú cho dân có bàn tay lụa), vì người dân nơi đây có bàn tay khéo léo, điệu nghệ, giỏi đan lát mây tre.
Và cứ thế, theo nghề “cha truyền con nối”, những đứa trẻ làng Phú Vinh lớn lên đã gắn bó với cây mây, cây tre, nắm lòng bàn tay các thuộc tính của từng cây tre, từng sợi mây. Dần dần, mây tre đan đã phát triển trở thành nghề truyền thống của làng Phú Vinh. Những người thợ lành nghề càng ngày càng tạo ra nhiều các sản phẩm mây tre đan đẹp mắt, tinh xảo, đa dạng về mẫu mã, chủng loại.', NULL, '2026-09-21T07:18:34.352Z', '2026-09-21T07:18:34.352Z')
ON CONFLICT (id) DO UPDATE SET
  "village_id" = EXCLUDED."village_id",
  "site_id" = EXCLUDED."site_id",
  "type" = EXCLUDED."type",
  "title" = EXCLUDED."title",
  "body_text" = EXCLUDED."body_text",
  "media_ids" = EXCLUDED."media_ids",
  "created_at" = EXCLUDED."created_at",
  "updated_at" = EXCLUDED."updated_at";
